import { OrganizationData } from './types';

export const defaultOrganizationData: OrganizationData = {
  settings: {
    id: 'general',
    org_name: 'Badan Eksekutif Mahasiswa Fakultas Hukum',
    slogan: 'Intelektual Muda Berintegritas, Progresif Membela Keadilan & Hak Mahasiswa',
    welcome_title: 'Selamat Datang di Portal Resmi Organisasi Mahasiswa Hukum',
    welcome_subtitle: 'Wadah perjuangan aspirasi mahasiswa, kajian hukum kritis, pengembangan peradilan semu (moot court), pembinaan paralegal muda, serta pengabdian masyarakat yang berintegritas dan independen.',
    logo_url: '/logo-bemfh.svg',
    hero_badge: 'Organisasi Mahasiswa Hukum Progresif & Berprestasi',
    hero_image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1600&q=80',
    cta_primary_label: 'Sampaikan Aspirasi Mahasiswa',
    cta_primary_url: '#kontak',
    cta_secondary_label: 'Lihat Agenda & Kegiatan',
    cta_secondary_url: '#kegiatan',
    sejarah: 'Badan Eksekutif Mahasiswa Fakultas Hukum didirikan sebagai representasi tertinggi mahasiswa hukum dalam memperjuangkan hak-hak akademik, kebebasan berpendapat, dan advokasi kesejahteraan civitas akademika di kampus. Berakar dari semangat reformasi peradilan dan Tri Dharma Perguruan Tinggi, organisasi ini konsisten melahirkan kader-kader intelektual yang kritis, menguasai keilmuan hukum teori maupun praktik (moot court), serta turun langsung mengabdi dan mendampingi persoalan hukum di tengah masyarakat.',
    visi: 'Terwujudnya organisasi kemahasiswaan hukum yang kritis, berintegritas moral, berdaya saing nasional, serta aktif memperjuangkan hak mahasiswa dan nilai keadilan substantif bagi masyarakat.',
    misi: [
      'Menjadi garda terdepan dalam menyerap, mengadvokasi, dan memperjuangkan aspirasi serta hak-hak mahasiswa di tingkat fakultas dan universitas.',
      'Menyelenggarakan forum kajian hukum kritis, riset kebijakan publik, dan diskusi ilmiah yang mencerdaskan civitas akademika.',
      'Memfasilitasi bakat dan kompetensi mahasiswa melalui kompetisi peradilan semu (National Moot Court), debat hukum, dan legal opinion.',
      'Mengabdi kepada masyarakat melalui klinik bantuan hukum mahasiswa, penyuluhan hukum desa binaan, dan aksi advokasi sosial.'
    ],
    instagram: 'bemfh.official',
    whatsapp: '6281234567890',
    email: 'aspirasi@bemfh-organisasi.id',
    alamat: 'Gedung Student Center Lt. 2, Fakultas Hukum, Kampus Universitas',
    maps_url: 'https://maps.google.com/?q=Fakultas+Hukum',
    jam_operasional: 'Senin - Jumat: 09.00 - 17.00 WIB | Sekretariat Organisasi Mahasiswa',
    primary_color: '#800020',
    font_family: 'Plus Jakarta Sans',
    font_heading: 'Plus Jakarta Sans',
    about_badge: 'Tentang Organisasi',
    about_title: 'Perjalanan Advokasi & Visi Keadilan',
    about_subtitle: 'Mengenal dedikasi, landasan nilai, serta susunan kepengurusan yang mengabdi bagi masyarakat dan mahasiswa.',
    pengurus_badge: 'Struktur Kepengurusan',
    pengurus_title: 'Pengurus & Fungsionaris BEM FH',
    pengurus_subtitle: 'Mahasiswa Fakultas Hukum yang berdedikasi mengabdi bagi almamater, sivitas akademika, dan masyarakat.',
    kegiatan_badge: 'Aktivitas & Agenda',
    kegiatan_title: 'Kegiatan & Jadwal Terbuka',
    kegiatan_subtitle: 'Ikuti agenda kegiatan kemahasiswaan, kajian hukum, serta program kerja terbaru.',
    galeri_badge: 'Dokumentasi Kegiatan',
    galeri_title: 'Galeri Foto Dokumentasi',
    galeri_subtitle: 'Potret komitmen dan dokumentasi kegiatan mahasiswa di kampus maupun masyarakat.',
    kontak_badge: 'Kontak Resmi',
    kontak_title: 'Hubungi Pengurus Organisasi',
    kontak_subtitle: 'Terhubung langsung dengan fungsionaris organisasi mahasiswa hukum melalui kanal komunikasi resmi di bawah ini:',
  },
  pengurus: [
    {
      id: 'p-1',
      nama: 'M. Rizky Pratama',
      gelar: 'Kandidat S.H.',
      jabatan: 'Ketua Umum / Gubernur Mahasiswa FH',
      divisi: 'Pengurus Inti',
      foto_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      urutan: 1,
      bio: 'Mahasiswa Hukum Angkatan 2023 dengan fokus Hukum Tata Negara, peraih Juara 1 National Moot Court Competition 2025.',
      kontak_email: 'ketua@bemfh-organisasi.id',
      is_active: true,
    },
    {
      id: 'p-2',
      nama: 'Anindya Putri Savitri',
      gelar: 'Kandidat S.H.',
      jabatan: 'Wakil Ketua Umum',
      divisi: 'Pengurus Inti',
      foto_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      urutan: 2,
      bio: 'Fokus Hukum Internasional, aktif mengoordinasikan program kerja strategis antardepartemen dan hubungan eksternal.',
      kontak_email: 'wakil@bemfh-organisasi.id',
      is_active: true,
    },
    {
      id: 'p-3',
      nama: 'Farhan Alfarizi',
      gelar: 'Kandidat S.H.',
      jabatan: 'Sekretaris Jenderal',
      divisi: 'Kesekretariatan',
      foto_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      urutan: 3,
      bio: 'Mengelola tata kelola persuratan, inventarisasi organisasi, dan arsip legal drafting lembaga kemahasiswaan.',
      kontak_email: 'sekretariat@bemfh-organisasi.id',
      is_active: true,
    },
    {
      id: 'p-4',
      nama: 'Dinda Permata Sari',
      gelar: 'Kandidat S.H.',
      jabatan: 'Bendahara Umum',
      divisi: 'Kebendaharaan',
      foto_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
      urutan: 4,
      bio: 'Bertanggung jawab atas transparansi sirkulasi anggaran kegiatan kemahasiswaan dan pendanaan delegasi lomba.',
      kontak_email: 'keuangan@bemfh-organisasi.id',
      is_active: true,
    },
    {
      id: 'p-5',
      nama: 'Reyhan Kusuma',
      gelar: 'Kandidat S.H.',
      jabatan: 'Kepala Dept. Kajian & Aksi Strategis (Kastrat)',
      divisi: 'Kajian & Aksi',
      foto_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
      urutan: 5,
      bio: 'Memimpin riset kritis regulasi, penyusunan naskah kajian akademik (policy brief), dan forum konsolidasi mahasiswa.',
      kontak_email: 'kastrat@bemfh-organisasi.id',
      is_active: true,
    },
    {
      id: 'p-6',
      nama: 'Sarah Azzahra',
      gelar: 'Kandidat S.H.',
      jabatan: 'Kepala Dept. Advokasi & Kesejahteraan Mahasiswa',
      divisi: 'Advokasi Kampus',
      foto_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
      urutan: 6,
      bio: 'Mengawal pendampingan banding UKT, mediasi fasilitas kampus, dan ruang aman aduan perlindungan hak mahasiswa.',
      kontak_email: 'adkesma@bemfh-organisasi.id',
      is_active: true,
    }
  ],
  kegiatan: [
    {
      id: 'k-1',
      judul: 'National Moot Court Competition (NMCC) & Gelar Peradilan Semu Mahasiswa',
      kategori: 'Pelatihan',
      tipe: 'kegiatan',
      tanggal: '2026-09-18',
      waktu: '08:30 - 17:00 WIB',
      lokasi: 'Ruang Sidang Semu Fakultas Hukum',
      deskripsi: 'Kompetisi simulasi sidang tindak pidana korupsi dan perdata bisnis tingkat nasional yang diikuti oleh 16 delegasi universitas ternama di Indonesia dengan dewan juri para hakim dan praktisi hukum profesional.',
      foto_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1000&q=80',
      is_featured: true,
    },
    {
      id: 'k-2',
      judul: 'Diskusi Publik Nasional: Menakar Integritas Hakim & Demokrasi Konstitusional',
      kategori: 'Edukasi',
      tipe: 'kegiatan',
      tanggal: '2026-09-05',
      waktu: '13:00 - 16:30 WIB',
      lokasi: 'Auditorium Utama Fakultas Hukum',
      deskripsi: 'Bedah dinamika hukum ketatanegaraan bersama akademisi dan pakar hukum, dihadiri oleh lebih dari 350 mahasiswa dan pegiat hukum muda secara luring dan daring.',
      foto_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1000&q=80',
      is_featured: false,
    },
    {
      id: 'k-3',
      judul: 'Klinik Advokasi & Pos Bantuan Aspirasi Kesejahteraan Mahasiswa',
      kategori: 'Advokasi',
      tipe: 'kegiatan',
      tanggal: '2026-09-25',
      waktu: '09:00 - 15:00 WIB',
      lokasi: 'Selasar Gedung Fakultas Hukum',
      deskripsi: 'Layanan pendampingan advokasi keringanan biaya kuliah (UKT), bantuan hukum perdata bagi mahasiswa yang mengalami penipuan kos-kosan, serta penampungan aspirasi fasilitas belajar.',
      foto_url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1000&q=80',
      is_featured: true,
    },
    {
      id: 'k-4',
      judul: 'Sekolah Legislatif & Pelatihan Legal Drafting Mahasiswa Hukum 2026',
      kategori: 'Pelatihan',
      tipe: 'agenda',
      tanggal: '2026-10-15',
      waktu: '08:30 - 15:00 WIB',
      lokasi: 'Ruang Seminar FH & Platform Zoom',
      deskripsi: 'Pelatihan intensif teknik perancangan peraturan perundang-undangan dan penyusunan kontrak perjanjian hukum dengan menghadirkan narasumber dari Badan Pembinaan Hukum Nasional.',
      foto_url: 'https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&w=1000&q=80',
      is_featured: true,
      link_pendaftaran: 'https://forms.gle/sekolah-legislatif-2026',
    },
    {
      id: 'k-5',
      judul: 'Desa Binaan: Program Penyuluhan Hukum Perlindungan Konsumen & Literasi Digital',
      kategori: 'Sosialisasi',
      tipe: 'agenda',
      tanggal: '2026-10-24',
      waktu: '08:00 - 14:00 WIB',
      lokasi: 'Balai Warga Desa Mitra Kampus',
      deskripsi: 'Aksi pengabdian masyarakat mahasiswa Fakultas Hukum dalam memberikan edukasi bahaya pinjaman online ilegal, penipuan digital, dan hak perlindungan konsumen di era modern.',
      foto_url: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1000&q=80',
      is_featured: false,
      link_pendaftaran: 'https://forms.gle/desa-binaan-mahasiswa',
    }
  ],
  galeri: [
    {
      id: 'g-1',
      judul: 'Delegasi Mahasiswa di National Moot Court Competition',
      deskripsi: 'Simulasi persidangan semu mempraktikkan pembuktian perkara di hadapan majelis hakim.',
      foto_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1000&q=80',
      tanggal: '2026-09-20',
      urutan: 1,
    },
    {
      id: 'g-2',
      judul: 'Forum Terbuka Dialog Dekanat & Aspirasi Mahasiswa',
      deskripsi: 'Penyampaian aspirasi mahasiswa terkait transparansi akademik dan fasilitas penunjang kampus.',
      foto_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1000&q=80',
      tanggal: '2026-09-15',
      urutan: 2,
    },
    {
      id: 'g-3',
      judul: 'Penyuluhan Hukum di Sekolah Menengah Atas Mitra',
      deskripsi: 'Edukasi kesadaran bahaya perundungan (cyberbullying) dan pengenalan UU ITE oleh mahasiswa FH.',
      foto_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1000&q=80',
      tanggal: '2026-08-30',
      urutan: 3,
    },
    {
      id: 'g-4',
      judul: 'Kunjungan Studi Institusi ke Mahkamah Konstitusi RI',
      deskripsi: 'Audiensi mahasiswa Fakultas Hukum memahami mekanisme uji materiil undang-undang.',
      foto_url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1000&q=80',
      tanggal: '2026-08-18',
      urutan: 4,
    },
    {
      id: 'g-5',
      judul: 'Pelantikan & Rapat Kerja Tahunan Kepengurusan BEM FH',
      deskripsi: 'Pengucapan sumpah komitmen memperjuangkan kepentingan almamater dan mahasiswa.',
      foto_url: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1000&q=80',
      tanggal: '2026-08-05',
      urutan: 5,
    },
    {
      id: 'g-6',
      judul: 'Diskusi Meja Bundar & Kajian Rutin Isu Hukum Terkini',
      deskripsi: 'Kajian intelektual mingguan membedah putusan hakim dan implikasi bagi keadilan publik.',
      foto_url: 'https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&w=1000&q=80',
      tanggal: '2026-07-22',
      urutan: 6,
    }
  ],
  pesan: [
    {
      id: 'm-1',
      nama: 'Dimas Anggara',
      email: 'dimas.angkatan24@student.ac.id',
      telepon: '081298765432',
      subjek: 'Konsultasi Banding Penurunan Golongan UKT Semester Genap',
      kategori_hukum: 'UKT & Finansial',
      pesan: 'Halo pengurus Adkesma BEM FH, saya mengalami kendala penurunan kemampuan ekonomi keluarga. Bagaimana prosedur berkas advokasi banding UKT ke bagian dekanat?',
      status: 'diproses',
      created_at: '2026-09-28T10:15:00Z',
    },
    {
      id: 'm-2',
      nama: 'Nabila Shafa',
      email: 'nabila.shafa@student.ac.id',
      telepon: '085712349876',
      subjek: 'Aspirasi Kebutuhan Ruang Belajar & Wifi di Selasar FH',
      kategori_hukum: 'Fasilitas Kampus',
      pesan: 'Mohon agar departemen advokasi bisa mengusulkan penambahan colokan listrik dan penguatan jaringan wifi di gazebo selasar fakultas untuk menunjang kegiatan belajar bersama.',
      status: 'belum_dibaca',
      created_at: '2026-09-30T14:20:00Z',
    }
  ]
};
